"use client";

import { useState } from "react";
import { useAuth } from "@/hooks/use-auth";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export function OnboardingFlow() {
  const { supabase, refreshHousehold, household, session } = useAuth();
  const router = useRouter();
  const userId = session?.user?.id;
  const [step, setStep] = useState<"choose" | "create" | "join">(
    household ? "choose" : "choose"
  );
  const [displayName, setDisplayName] = useState("");
  const [inviteCode, setInviteCode] = useState("");
  const [avatarColor, setAvatarColor] = useState("#FF6B6B");
  const [generatedCode, setGeneratedCode] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (household) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="text-center space-y-4">
          <p className="text-muted-foreground">You&apos;re already part of a household.</p>
          <Button onClick={() => router.push("/board")}>Go to Board</Button>
        </div>
      </div>
    );
  }

  const handleCreate = async () => {
    if (!displayName.trim()) return;
    setLoading(true);
    setError(null);

    const { data: hh, error: hhError } = await supabase
      .from("households")
      .insert({})
      .select()
      .single();

    if (hhError) {
      setError(hhError.message);
      setLoading(false);
      return;
    }

    // invite_code is auto-generated by DB trigger — no need to set it

    const { error: memberError } = await supabase
      .from("household_members")
      .insert({ household_id: hh.id, user_id: userId });

    if (memberError) {
      setError(memberError.message);
      setLoading(false);
      return;
    }

    await supabase
      .from("users")
      .upsert({
        id: userId,
        email: session?.user?.email,
        display_name: displayName.trim(),
        avatar_color: avatarColor,
      });

    setGeneratedCode(hh.invite_code);
    setLoading(false);
  };

  const handleJoin = async () => {
    if (!inviteCode.trim() || !displayName.trim()) return;
    setLoading(true);
    setError(null);

    const { data: hh } = await supabase
      .from("households")
      .select("*")
      .eq("invite_code", inviteCode.trim().toUpperCase())
      .maybeSingle();

    if (!hh) {
      setError("Invalid invite code. Please check and try again.");
      setLoading(false);
      return;
    }

    const { data: existingMembers } = await supabase
      .from("household_members")
      .select("*")
      .eq("household_id", hh.id);

    if ((existingMembers?.length ?? 0) >= 2) {
      setError("This household already has 2 members.");
      setLoading(false);
      return;
    }

    const { error: memberError } = await supabase
      .from("household_members")
      .insert({ household_id: hh.id, user_id: userId });

    if (memberError) {
      setError(memberError.message);
      setLoading(false);
      return;
    }

    await supabase
      .from("users")
      .upsert({
        id: userId,
        email: session?.user?.email,
        display_name: displayName.trim(),
        avatar_color: avatarColor,
      });

    await refreshHousehold();
    router.push("/board");
    setLoading(false);
  };

  if (generatedCode) {
    return (
      <Card className="max-w-md mx-auto">
        <CardHeader>
          <CardTitle>Household Created</CardTitle>
          <CardDescription>
            Share this code with your partner to join:
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="text-center">
            <span className="text-4xl font-mono font-bold tracking-widest bg-muted px-6 py-3 rounded-lg">
              {generatedCode}
            </span>
          </div>
          <p className="text-sm text-muted-foreground text-center">
            They will enter this code on their device to join your household.
          </p>
          <Button
            className="w-full"
            onClick={() => {
              refreshHousehold().then(() => router.push("/board"));
            }}
          >
            Continue to Board
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="max-w-md mx-auto">
      <CardHeader>
        <CardTitle>
          {step === "choose"
            ? "Welcome to WeekSync"
            : step === "create"
            ? "Create Household"
            : "Join Household"}
        </CardTitle>
        <CardDescription>
          {step === "choose"
            ? "Get started by creating or joining a household."
            : step === "create"
            ? "Set up your household and invite your partner."
            : "Enter your partner's invite code to join."}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {error && (
          <div className="text-sm text-destructive bg-destructive/10 p-3 rounded-md">
            {error}
          </div>
        )}

        {step === "choose" && (
          <div className="space-y-3">
            <Button className="w-full" size="lg" onClick={() => setStep("create")}>
              Create a New Household
            </Button>
            <Button
              className="w-full"
              size="lg"
              variant="outline"
              onClick={() => setStep("join")}
            >
              Join an Existing Household
            </Button>
          </div>
        )}

        {(step === "create" || step === "join") && (
          <>
            <div className="space-y-2">
              <Label htmlFor="displayName">Display Name</Label>
              <Input
                id="displayName"
                placeholder="Your name"
                value={displayName}
                onChange={(e) => setDisplayName(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Avatar Color</Label>
              <div className="flex gap-2 flex-wrap">
                {["#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FFEAA7", "#DDA0DD", "#98D8C8", "#F7DC6F", "#BB8FCE", "#85C1E9"].map(
                  (color) => (
                    <button
                      key={color}
                      onClick={() => setAvatarColor(color)}
                      className="w-8 h-8 rounded-full border-2 transition-all"
                      style={{
                        backgroundColor: color,
                        borderColor: avatarColor === color ? "hsl(var(--foreground))" : "transparent",
                        transform: avatarColor === color ? "scale(1.15)" : "scale(1)",
                      }}
                    />
                  )
                )}
              </div>
            </div>

            {step === "join" && (
              <div className="space-y-2">
                <Label htmlFor="inviteCode">Invite Code</Label>
                <Input
                  id="inviteCode"
                  placeholder="ABC123"
                  value={inviteCode}
                  onChange={(e) => setInviteCode(e.target.value.toUpperCase())}
                  className="font-mono text-center text-lg tracking-widest"
                  maxLength={6}
                />
              </div>
            )}

            <div className="flex gap-3 pt-2">
              <Button variant="outline" onClick={() => setStep("choose")}>
                Back
              </Button>
              <Button
                className="flex-1"
                onClick={step === "create" ? handleCreate : handleJoin}
                disabled={loading}
              >
                {loading ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : step === "create" ? (
                  "Create Household"
                ) : (
                  "Join Household"
                )}
              </Button>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}
